//go:build !ignore_autogenerated

// Code generated by controller-gen style conventions. DO NOT EDIT.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *CapabilityConsumption) DeepCopyInto(out *CapabilityConsumption) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *CapabilityConsumption) DeepCopy() *CapabilityConsumption {
	if in == nil {
		return nil
	}
	out := new(CapabilityConsumption)
	in.DeepCopyInto(out)
	return out
}

func (in *CapabilityConsumption) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CapabilityConsumptionList) DeepCopyInto(out *CapabilityConsumptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapabilityConsumption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *CapabilityConsumptionList) DeepCopy() *CapabilityConsumptionList {
	if in == nil {
		return nil
	}
	out := new(CapabilityConsumptionList)
	in.DeepCopyInto(out)
	return out
}

func (in *CapabilityConsumptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CapabilityConsumptionSpec) DeepCopyInto(out *CapabilityConsumptionSpec) {
	*out = *in
	if in.ExternalPlatforms != nil {
		in, out := &in.ExternalPlatforms, &out.ExternalPlatforms
		*out = make(map[string]ExternalPlatformSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OwnedCapabilities != nil {
		in, out := &in.OwnedCapabilities, &out.OwnedCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *CapabilityConsumptionStatus) DeepCopyInto(out *CapabilityConsumptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceReference, len(*in))
		copy(*out, *in)
	}
}
