apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: REPLACE_ME
  namespace: REPLACE_ME
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: REPLACE_ME
    kind: ClusterSecretStore
  target:
    name: REPLACE_ME
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: REPLACE_ME
