apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mayabank-product-consumers
  namespace: openshift-gitops
spec:
  description: MayaBank product consumers of shared platform services
  sourceRepos:
    - https://github.com/zdmooc/mayabank-customer-identity-kyc-digital-banking-architecture.git
  destinations:
    - namespace: customer-digital
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
