apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-kyc-digital
  namespace: openshift-gitops
  labels:
    platform.mayabank.example/consumer: customer-kyc-digital
spec:
  project: mayabank-product-consumers
  source:
    repoURL: https://github.com/zdmooc/mayabank-customer-identity-kyc-digital-banking-architecture.git
    targetRevision: main
    path: platform-consumption/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-digital
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
